version: 2
updates:
- package-ecosystem: cargo
  directory: "/crate/wisp/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  ignore:
    - dependency-name: "wisp"
